### PR TITLE
Random bitstring dataset

### PR DESCRIPTION
**Pull request by maumueller**

### CODE REVIEW

**Comment by maumueller** [comment]
Added some more datasets and made them dimensionality a multiple of 8, which fixed some problems with mih. Should be ready to be merged from my side.

**Comment by ale-f** [comment]
Ah, I found a fun bug -- `get_dataset` in `ann_benchmarks/datasets.py` is supposed to generate the dataset if Erik's server doesn't have a pre-generated copy, but it fails, because it downloads the 404 error and concludes that that error *is* the dataset. :-) I'll fix that after this has been merged.

I'm having some minor problems running the tests (dictionary lookups fail all over the place; something to do with Unicode?); I'll make sure I can run them and then merge this afterwards.

**Comment by ale-f** [comment]
OK; for some reason datasets *need* to be created with Python 3 for them to work properly with either Python 2 or Python 3. Then it works. Odd...

I note that `wrapper/protocol.c` in MIH doesn't support batch mode, but `ann_benchmarks.algorithms.Subprocess` doesn't seem to handle that properly and crashes in a weird way. I'll have a quick look at that before I merge this.

**Comment by ale-f** [comment]
Oh, wait, I'm wrong; it's nothing to do with batch mode, there are just some combinations of configuration parameters that make the subprocess wrapper crash with `SIGSEGV` when training mode ends.

Does this one, for example, succeed for you?

```
(Definition(algorithm='mih', constructor='BitSubprocessPrepared', module='ann_benchmarks.algorithms.subprocess', docker_tag='ann-benchmarks-mih', arguments=[['mih/bin/mihwrapper'], {'r': 2, 'd': 16, 'chunk-factor': 0}], query_argument_groups=[], disabled=False), '...')
Running command ['--dataset', 'random-xs-16-hamming', '--algorithm', 'mih', '--module', 'ann_benchmarks.algorithms.subprocess', '--constructor', 'BitSubprocessPrepared', '--runs', '2', '--count', '10', '[["mih/bin/mihwrapper"], {"r": 2, "d": 16, "chunk-factor": 0}]']
```

I just get this error when it tries to transition to query mode:

```
Traceback (most recent call last):
  File "run_algorithm.py", line 3, in <module>
    run_from_cmdline()
  File "/home/app/ann_benchmarks/runner.py", line 195, in run_from_cmdline
    run(definition, args.dataset, args.count, args.runs, args.batch)
  File "/home/app/ann_benchmarks/runner.py", line 121, in run
    algo.fit(X_train)
  File "/home/app/ann_benchmarks/algorithms/subprocess.py", line 84, in fit
    assert self._line()[0] == "ok", """\
  File "/home/app/ann_benchmarks/algorithms/subprocess.py", line 24, in _line
    line = self._raw_line()
  File "/home/app/ann_benchmarks/algorithms/subprocess.py", line 19, in _raw_line
    self._get_program_handle().stdout.readline().strip())
  File "/home/app/ann_benchmarks/algorithms/subprocess.py", line 43, in _get_program_handle
    raise SubprocessStoppedError(self._program.returncode)
ann_benchmarks.algorithms.subprocess.SubprocessStoppedError: -11
```

**Comment by ale-f** [comment]
That looks good now; merged. Thanks!

**Pull request merged**
